# Generated by Django 5.1.2 on 2024-10-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_role',
            field=models.IntegerField(choices=[(1, 'Admin'), (3, 'Customer Support Staff'), (2, 'Moderator')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_by',
            field=models.IntegerField(blank=True, choices=[(3, 'Google'), (1, 'General'), (4, 'Facebook'), (2, 'Guest')], default=1, null=True),
        ),
    ]
