# Generated by Django 5.1.2 on 2024-12-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_discount_amount_order_gift_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_role',
            field=models.IntegerField(blank=True, choices=[(1, 'Admin'), (3, 'Customer Support Staff'), (2, 'Moderator')], default=0, null=True),
        ),
    ]
