# Generated by Django 5.1.2 on 2024-10-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_user_is_role_alter_user_login_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_role',
            field=models.IntegerField(blank=True, choices=[(2, 'Moderator'), (3, 'Customer Support Staff'), (1, 'Admin')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_by',
            field=models.IntegerField(blank=True, choices=[(4, 'Facebook'), (2, 'Guest'), (1, 'General'), (3, 'Google')], default=1, null=True),
        ),
    ]
