# Generated by Django 5.1.3 on 2024-12-19 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_user_is_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_role',
            field=models.IntegerField(blank=True, choices=[(3, 'Customer Support Staff'), (1, 'Admin'), (2, 'Moderator')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_by',
            field=models.IntegerField(blank=True, choices=[(1, 'General'), (2, 'Guest'), (4, 'Facebook'), (3, 'Google')], default=1, null=True),
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('address_line1', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.billingaddress'),
        ),
    ]
