# Generated by Django 5.1.3 on 2024-12-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_status_alter_user_is_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_id',
            new_name='razorpay_order_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_signature',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_response',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_role',
            field=models.IntegerField(blank=True, choices=[(3, 'Customer Support Staff'), (2, 'Moderator'), (1, 'Admin')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_by',
            field=models.IntegerField(blank=True, choices=[(1, 'General'), (2, 'Guest'), (3, 'Google'), (4, 'Facebook')], default=1, null=True),
        ),
    ]
