# Generated by Django 5.1.2 on 2024-12-22 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_payment_id_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_payment', to='store.payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payments', to='store.order'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_role',
            field=models.IntegerField(blank=True, choices=[(2, 'Moderator'), (3, 'Customer Support Staff'), (1, 'Admin')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_by',
            field=models.IntegerField(blank=True, choices=[(2, 'Guest'), (4, 'Facebook'), (3, 'Google'), (1, 'General')], default=1, null=True),
        ),
    ]
