# Generated by Django 5.1.4 on 2025-01-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_payment_alter_payment_order_alter_user_is_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_role',
            field=models.IntegerField(blank=True, choices=[(3, 'Customer Support Staff'), (1, 'Admin'), (2, 'Moderator')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_by',
            field=models.IntegerField(blank=True, choices=[(4, 'Facebook'), (1, 'General'), (3, 'Google'), (2, 'Guest')], default=1, null=True),
        ),
    ]
